// <auto-generated />
using System;
using Jazzima1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jazzima1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200212031936_updatedBassPLayer")]
    partial class updatedBassPLayer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jazzima1.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://upload.wikimedia.org/wikipedia/en/7/7a/Maiden_Voyage_%28Hancock%29.jpg",
                            ReleaseDate = 1965,
                            Title = "Maiden Voyage"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://upload.wikimedia.org/wikipedia/en/4/4a/Point_of_Departure.jpg",
                            ReleaseDate = 1965,
                            Title = "Point Of Departure"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://upload.wikimedia.org/wikipedia/en/4/41/The_Soothsayer.jpg",
                            ReleaseDate = 1979,
                            Title = "The Soothsayer"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://upload.wikimedia.org/wikipedia/en/c/c0/Horace_Silver_and_the_Jazz_Messengers.jpg",
                            ReleaseDate = 1956,
                            Title = "Horace Silver and The Jazz Messengers"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://upload.wikimedia.org/wikipedia/en/6/68/John_Coltrane_-_Blue_Train.jpg",
                            ReleaseDate = 1958,
                            Title = "Blue Train"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://upload.wikimedia.org/wikipedia/en/e/ec/The_Cooker.jpg",
                            ReleaseDate = 1958,
                            Title = "The Cooker"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://upload.wikimedia.org/wikipedia/commons/a/ad/Somethin%E2%80%99_Else.jpg",
                            ReleaseDate = 1958,
                            Title = "Somethin' Else"
                        },
                        new
                        {
                            Id = 8,
                            Image = "https://upload.wikimedia.org/wikipedia/en/3/32/Newk%27s_Time.jpeg",
                            ReleaseDate = 1959,
                            Title = "Newk's Time"
                        },
                        new
                        {
                            Id = 9,
                            Image = "https://upload.wikimedia.org/wikipedia/en/0/0e/Off_to_the_Races.jpg",
                            ReleaseDate = 1959,
                            Title = "Off To The Races"
                        },
                        new
                        {
                            Id = 10,
                            Image = "https://upload.wikimedia.org/wikipedia/en/7/78/New_Soil.jpg",
                            ReleaseDate = 1959,
                            Title = "New Soil"
                        },
                        new
                        {
                            Id = 11,
                            Image = "https://upload.wikimedia.org/wikipedia/en/f/f1/Davis_Cup_%28album%29.jpg",
                            ReleaseDate = 1960,
                            Title = "Davis Cup"
                        },
                        new
                        {
                            Id = 12,
                            Image = "https://upload.wikimedia.org/wikipedia/en/d/d1/Open_Sesame_%28Freddie_Hubbard_album%29.jpg",
                            ReleaseDate = 1960,
                            Title = "Open Sesame"
                        },
                        new
                        {
                            Id = 13,
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/94/AT%27s_Delight.jpg",
                            ReleaseDate = 1960,
                            Title = "A.T's Delight"
                        },
                        new
                        {
                            Id = 14,
                            Image = "https://upload.wikimedia.org/wikipedia/en/5/5f/PageOne.jpg",
                            ReleaseDate = 1963,
                            Title = "Page One"
                        },
                        new
                        {
                            Id = 15,
                            Image = "https://upload.wikimedia.org/wikipedia/en/e/e3/UnaMasDorham.jpg",
                            ReleaseDate = 1963,
                            Title = "Una Mas"
                        },
                        new
                        {
                            Id = 16,
                            Image = "https://upload.wikimedia.org/wikipedia/en/e/e2/Lee_Morgan-The_Sidewinder_%28album_cover%29.jpg",
                            ReleaseDate = 1964,
                            Title = "The Sidewinder"
                        },
                        new
                        {
                            Id = 17,
                            Image = "https://upload.wikimedia.org/wikipedia/en/9/9e/No_Room_for_Squares.jpg",
                            ReleaseDate = 1963,
                            Title = "No Room For Squares"
                        },
                        new
                        {
                            Id = 18,
                            Image = "https://upload.wikimedia.org/wikipedia/en/c/cc/Dolphy_Out_To_Lunch.png",
                            ReleaseDate = 1964,
                            Title = "Out To Lunch"
                        },
                        new
                        {
                            Id = 19,
                            Image = "https://upload.wikimedia.org/wikipedia/en/a/a3/The_Freedom_Rider.jpg",
                            ReleaseDate = 1964,
                            Title = "The Freedom Rider"
                        },
                        new
                        {
                            Id = 20,
                            Image = "https://upload.wikimedia.org/wikipedia/en/b/bc/A_Night_in_Tunisia_%281960_album%29.jpg",
                            ReleaseDate = 1961,
                            Title = "A Night In Tunisia"
                        },
                        new
                        {
                            Id = 21,
                            Image = "https://upload.wikimedia.org/wikipedia/en/c/ca/Bluesnik.jpg",
                            ReleaseDate = 1962,
                            Title = "Bluesnik"
                        },
                        new
                        {
                            Id = 22,
                            Image = "https://upload.wikimedia.org/wikipedia/en/2/22/One_Flight_Up.jpg",
                            ReleaseDate = 1965,
                            Title = "One Flight Up"
                        },
                        new
                        {
                            Id = 23,
                            Image = "https://upload.wikimedia.org/wikipedia/en/7/78/The_Thing_to_Do_%28album%29.jpg",
                            ReleaseDate = 1965,
                            Title = "The Thing To Do"
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Jazzima1.Models.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InstrumentType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Horn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Piano"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bass"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Drums"
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Instrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstrumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentTypeId");

                    b.ToTable("Musician");

                    b.HasData(
                        new
                        {
                            Id = 5,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Herbie Hancock"
                        },
                        new
                        {
                            Id = 6,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Freddie Hubbard"
                        },
                        new
                        {
                            Id = 7,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "George Coleman"
                        },
                        new
                        {
                            Id = 8,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Ron Carter"
                        },
                        new
                        {
                            Id = 9,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Tony Williams"
                        },
                        new
                        {
                            Id = 10,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Kenny Dorham"
                        },
                        new
                        {
                            Id = 11,
                            Instrument = "alto saxophone",
                            InstrumentTypeId = 1,
                            Name = "Eric Dolphy"
                        },
                        new
                        {
                            Id = 12,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Joe Henderson"
                        },
                        new
                        {
                            Id = 13,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Andrew Hill"
                        },
                        new
                        {
                            Id = 14,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Richard Davis"
                        },
                        new
                        {
                            Id = 15,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Wayne Shorter"
                        },
                        new
                        {
                            Id = 16,
                            Instrument = "alto saxophone",
                            InstrumentTypeId = 1,
                            Name = "James Spaulding"
                        },
                        new
                        {
                            Id = 17,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "McCoy Tyner"
                        },
                        new
                        {
                            Id = 18,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Horace Silver"
                        },
                        new
                        {
                            Id = 19,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Hank Mobley"
                        },
                        new
                        {
                            Id = 20,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Doug Watkins"
                        },
                        new
                        {
                            Id = 21,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Art Blakey"
                        },
                        new
                        {
                            Id = 22,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Philly Joe Jones"
                        },
                        new
                        {
                            Id = 23,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Paul Chambers"
                        },
                        new
                        {
                            Id = 24,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Kenny Drew"
                        },
                        new
                        {
                            Id = 25,
                            Instrument = "trombone",
                            InstrumentTypeId = 1,
                            Name = "Curtis Fuller"
                        },
                        new
                        {
                            Id = 26,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Lee Morgan"
                        },
                        new
                        {
                            Id = 27,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "John Coltrane"
                        },
                        new
                        {
                            Id = 28,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Bobby Timmons"
                        },
                        new
                        {
                            Id = 29,
                            Instrument = "baritone saxophone",
                            InstrumentTypeId = 1,
                            Name = "Pepper Adams"
                        },
                        new
                        {
                            Id = 30,
                            Instrument = "alto saxophone",
                            InstrumentTypeId = 1,
                            Name = "Cannonball Adderley"
                        },
                        new
                        {
                            Id = 31,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Miles Davis"
                        },
                        new
                        {
                            Id = 32,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Hank Jones"
                        },
                        new
                        {
                            Id = 33,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Sam Jones"
                        },
                        new
                        {
                            Id = 34,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Sonny Rollins"
                        },
                        new
                        {
                            Id = 35,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Wynton Kelly"
                        },
                        new
                        {
                            Id = 36,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Donald Byrd"
                        },
                        new
                        {
                            Id = 37,
                            Instrument = "alto saxophone",
                            InstrumentTypeId = 1,
                            Name = "Jackie McLean"
                        },
                        new
                        {
                            Id = 38,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Sam Jones"
                        },
                        new
                        {
                            Id = 39,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Art Taylor"
                        },
                        new
                        {
                            Id = 40,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Walter Davis Jr."
                        },
                        new
                        {
                            Id = 41,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Pete La Roca"
                        },
                        new
                        {
                            Id = 42,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Clifford Jarvis"
                        },
                        new
                        {
                            Id = 43,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Stanley Turrentine"
                        },
                        new
                        {
                            Id = 44,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Butch Warren"
                        },
                        new
                        {
                            Id = 45,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Barry Harris"
                        },
                        new
                        {
                            Id = 46,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Bob Cranshaw"
                        },
                        new
                        {
                            Id = 47,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Billy Higgins"
                        },
                        new
                        {
                            Id = 48,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Jymie Merritt"
                        },
                        new
                        {
                            Id = 49,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Dexter Gordon"
                        },
                        new
                        {
                            Id = 50,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Niels-Henning Ørsted"
                        },
                        new
                        {
                            Id = 51,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Blue Mitchell"
                        },
                        new
                        {
                            Id = 52,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Junior Cook"
                        },
                        new
                        {
                            Id = 53,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Chick Corea"
                        },
                        new
                        {
                            Id = 54,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Gene Taylor"
                        },
                        new
                        {
                            Id = 55,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Al Foster"
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.MusicianAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("MusicianId");

                    b.ToTable("MusicianAlbum");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            MusicianId = 5
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            MusicianId = 6
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            MusicianId = 6
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 1,
                            MusicianId = 7
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 2,
                            MusicianId = 10
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 2,
                            MusicianId = 11
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 2,
                            MusicianId = 12
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 2,
                            MusicianId = 13
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 2,
                            MusicianId = 14
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 3,
                            MusicianId = 15
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 3,
                            MusicianId = 16
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 3,
                            MusicianId = 17
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 1,
                            MusicianId = 9
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 2,
                            MusicianId = 9
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 1,
                            MusicianId = 8
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 3,
                            MusicianId = 8
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 4,
                            MusicianId = 18
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 4,
                            MusicianId = 10
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 4,
                            MusicianId = 19
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 4,
                            MusicianId = 20
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 4,
                            MusicianId = 21
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 5,
                            MusicianId = 27
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 5,
                            MusicianId = 25
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 5,
                            MusicianId = 24
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 5,
                            MusicianId = 26
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 5,
                            MusicianId = 23
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 5,
                            MusicianId = 22
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 6,
                            MusicianId = 26
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 6,
                            MusicianId = 29
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 6,
                            MusicianId = 28
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 6,
                            MusicianId = 23
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 6,
                            MusicianId = 22
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 7,
                            MusicianId = 30
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 7,
                            MusicianId = 31
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 7,
                            MusicianId = 32
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 7,
                            MusicianId = 33
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 7,
                            MusicianId = 21
                        },
                        new
                        {
                            Id = 38,
                            AlbumId = 8,
                            MusicianId = 34
                        },
                        new
                        {
                            Id = 39,
                            AlbumId = 8,
                            MusicianId = 35
                        },
                        new
                        {
                            Id = 40,
                            AlbumId = 8,
                            MusicianId = 20
                        },
                        new
                        {
                            Id = 41,
                            AlbumId = 8,
                            MusicianId = 22
                        },
                        new
                        {
                            Id = 42,
                            AlbumId = 9,
                            MusicianId = 36
                        },
                        new
                        {
                            Id = 43,
                            AlbumId = 9,
                            MusicianId = 37
                        },
                        new
                        {
                            Id = 44,
                            AlbumId = 9,
                            MusicianId = 29
                        },
                        new
                        {
                            Id = 45,
                            AlbumId = 9,
                            MusicianId = 35
                        },
                        new
                        {
                            Id = 46,
                            AlbumId = 9,
                            MusicianId = 38
                        },
                        new
                        {
                            Id = 47,
                            AlbumId = 9,
                            MusicianId = 39
                        },
                        new
                        {
                            Id = 48,
                            AlbumId = 10,
                            MusicianId = 37
                        },
                        new
                        {
                            Id = 49,
                            AlbumId = 10,
                            MusicianId = 36
                        },
                        new
                        {
                            Id = 50,
                            AlbumId = 10,
                            MusicianId = 40
                        },
                        new
                        {
                            Id = 51,
                            AlbumId = 10,
                            MusicianId = 23
                        },
                        new
                        {
                            Id = 52,
                            AlbumId = 10,
                            MusicianId = 41
                        },
                        new
                        {
                            Id = 53,
                            AlbumId = 11,
                            MusicianId = 40
                        },
                        new
                        {
                            Id = 54,
                            AlbumId = 11,
                            MusicianId = 36
                        },
                        new
                        {
                            Id = 55,
                            AlbumId = 11,
                            MusicianId = 37
                        },
                        new
                        {
                            Id = 56,
                            AlbumId = 11,
                            MusicianId = 38
                        },
                        new
                        {
                            Id = 57,
                            AlbumId = 11,
                            MusicianId = 39
                        },
                        new
                        {
                            Id = 58,
                            AlbumId = 12,
                            MusicianId = 6
                        },
                        new
                        {
                            Id = 59,
                            AlbumId = 12,
                            MusicianId = 17
                        },
                        new
                        {
                            Id = 60,
                            AlbumId = 12,
                            MusicianId = 38
                        },
                        new
                        {
                            Id = 61,
                            AlbumId = 12,
                            MusicianId = 42
                        },
                        new
                        {
                            Id = 62,
                            AlbumId = 13,
                            MusicianId = 43
                        },
                        new
                        {
                            Id = 63,
                            AlbumId = 13,
                            MusicianId = 35
                        },
                        new
                        {
                            Id = 64,
                            AlbumId = 13,
                            MusicianId = 23
                        },
                        new
                        {
                            Id = 65,
                            AlbumId = 13,
                            MusicianId = 39
                        },
                        new
                        {
                            Id = 66,
                            AlbumId = 14,
                            MusicianId = 12
                        },
                        new
                        {
                            Id = 67,
                            AlbumId = 14,
                            MusicianId = 10
                        },
                        new
                        {
                            Id = 68,
                            AlbumId = 14,
                            MusicianId = 17
                        },
                        new
                        {
                            Id = 69,
                            AlbumId = 14,
                            MusicianId = 44
                        },
                        new
                        {
                            Id = 70,
                            AlbumId = 14,
                            MusicianId = 41
                        },
                        new
                        {
                            Id = 71,
                            AlbumId = 15,
                            MusicianId = 10
                        },
                        new
                        {
                            Id = 72,
                            AlbumId = 15,
                            MusicianId = 12
                        },
                        new
                        {
                            Id = 73,
                            AlbumId = 15,
                            MusicianId = 5
                        },
                        new
                        {
                            Id = 74,
                            AlbumId = 15,
                            MusicianId = 44
                        },
                        new
                        {
                            Id = 75,
                            AlbumId = 15,
                            MusicianId = 9
                        },
                        new
                        {
                            Id = 76,
                            AlbumId = 16,
                            MusicianId = 26
                        },
                        new
                        {
                            Id = 77,
                            AlbumId = 16,
                            MusicianId = 12
                        },
                        new
                        {
                            Id = 78,
                            AlbumId = 16,
                            MusicianId = 45
                        },
                        new
                        {
                            Id = 79,
                            AlbumId = 16,
                            MusicianId = 46
                        },
                        new
                        {
                            Id = 80,
                            AlbumId = 16,
                            MusicianId = 47
                        },
                        new
                        {
                            Id = 81,
                            AlbumId = 17,
                            MusicianId = 19
                        },
                        new
                        {
                            Id = 82,
                            AlbumId = 17,
                            MusicianId = 26
                        },
                        new
                        {
                            Id = 83,
                            AlbumId = 17,
                            MusicianId = 13
                        },
                        new
                        {
                            Id = 84,
                            AlbumId = 17,
                            MusicianId = 44
                        },
                        new
                        {
                            Id = 85,
                            AlbumId = 17,
                            MusicianId = 22
                        },
                        new
                        {
                            Id = 86,
                            AlbumId = 18,
                            MusicianId = 11
                        },
                        new
                        {
                            Id = 87,
                            AlbumId = 18,
                            MusicianId = 6
                        },
                        new
                        {
                            Id = 88,
                            AlbumId = 18,
                            MusicianId = 14
                        },
                        new
                        {
                            Id = 89,
                            AlbumId = 18,
                            MusicianId = 9
                        },
                        new
                        {
                            Id = 90,
                            AlbumId = 19,
                            MusicianId = 21
                        },
                        new
                        {
                            Id = 91,
                            AlbumId = 19,
                            MusicianId = 26
                        },
                        new
                        {
                            Id = 92,
                            AlbumId = 19,
                            MusicianId = 15
                        },
                        new
                        {
                            Id = 93,
                            AlbumId = 19,
                            MusicianId = 28
                        },
                        new
                        {
                            Id = 94,
                            AlbumId = 19,
                            MusicianId = 48
                        },
                        new
                        {
                            Id = 95,
                            AlbumId = 20,
                            MusicianId = 26
                        },
                        new
                        {
                            Id = 96,
                            AlbumId = 20,
                            MusicianId = 15
                        },
                        new
                        {
                            Id = 97,
                            AlbumId = 20,
                            MusicianId = 28
                        },
                        new
                        {
                            Id = 98,
                            AlbumId = 20,
                            MusicianId = 48
                        },
                        new
                        {
                            Id = 99,
                            AlbumId = 20,
                            MusicianId = 21
                        },
                        new
                        {
                            Id = 100,
                            AlbumId = 21,
                            MusicianId = 37
                        },
                        new
                        {
                            Id = 101,
                            AlbumId = 21,
                            MusicianId = 6
                        },
                        new
                        {
                            Id = 102,
                            AlbumId = 21,
                            MusicianId = 24
                        },
                        new
                        {
                            Id = 103,
                            AlbumId = 21,
                            MusicianId = 20
                        },
                        new
                        {
                            Id = 104,
                            AlbumId = 21,
                            MusicianId = 41
                        },
                        new
                        {
                            Id = 105,
                            AlbumId = 22,
                            MusicianId = 49
                        },
                        new
                        {
                            Id = 106,
                            AlbumId = 22,
                            MusicianId = 36
                        },
                        new
                        {
                            Id = 107,
                            AlbumId = 22,
                            MusicianId = 24
                        },
                        new
                        {
                            Id = 108,
                            AlbumId = 22,
                            MusicianId = 50
                        },
                        new
                        {
                            Id = 109,
                            AlbumId = 22,
                            MusicianId = 39
                        },
                        new
                        {
                            Id = 110,
                            AlbumId = 23,
                            MusicianId = 51
                        },
                        new
                        {
                            Id = 111,
                            AlbumId = 23,
                            MusicianId = 52
                        },
                        new
                        {
                            Id = 112,
                            AlbumId = 23,
                            MusicianId = 53
                        },
                        new
                        {
                            Id = 113,
                            AlbumId = 23,
                            MusicianId = 54
                        },
                        new
                        {
                            Id = 114,
                            AlbumId = 23,
                            MusicianId = 55
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.SavedAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("SavedAlbums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 4,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 5,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 6,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 7,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 8,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 9,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 10,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Jazzima1.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "00000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cbd56e8b-d9e3-4ff7-bc9a-a74b4f712f21",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEMYHWhd1JZMIQ86JZBWGzL9gmNklADO/IAN4MUAuP07i6rYJUjnPVqsPqV7aKOzcGg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com",
                            FirstName = "admin",
                            LastName = "admin"
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.Comments", b =>
                {
                    b.HasOne("Jazzima1.Models.Album", "Album")
                        .WithMany("Comments")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jazzima1.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Jazzima1.Models.Musician", b =>
                {
                    b.HasOne("Jazzima1.Models.InstrumentType", "InstrumentType")
                        .WithMany()
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jazzima1.Models.MusicianAlbum", b =>
                {
                    b.HasOne("Jazzima1.Models.Album", "Album")
                        .WithMany("MusicianAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jazzima1.Models.Musician", "Musician")
                        .WithMany("MusicianAlbums")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jazzima1.Models.SavedAlbum", b =>
                {
                    b.HasOne("Jazzima1.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
