// <auto-generated />
using System;
using Jazzima1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Jazzima1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200207225756_rebuildingDB")]
    partial class rebuildingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Jazzima1.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReleaseDate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://upload.wikimedia.org/wikipedia/en/7/7a/Maiden_Voyage_%28Hancock%29.jpg",
                            ReleaseDate = 1965,
                            Title = "Maiden Voyage"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://upload.wikimedia.org/wikipedia/en/4/4a/Point_of_Departure.jpg",
                            ReleaseDate = 1965,
                            Title = "Point Of Departure"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://upload.wikimedia.org/wikipedia/en/4/41/The_Soothsayer.jpg",
                            ReleaseDate = 1979,
                            Title = "The Soothsayer"
                        },
                        new
                        {
                            Id = 4,
                            Image = "https://upload.wikimedia.org/wikipedia/en/c/c0/Horace_Silver_and_the_Jazz_Messengers.jpg",
                            ReleaseDate = 1956,
                            Title = "Horace Silver and The Jazz Messengers"
                        },
                        new
                        {
                            Id = 5,
                            Image = "https://upload.wikimedia.org/wikipedia/en/6/68/John_Coltrane_-_Blue_Train.jpg",
                            ReleaseDate = 1958,
                            Title = "Blue Train"
                        },
                        new
                        {
                            Id = 6,
                            Image = "https://upload.wikimedia.org/wikipedia/en/e/ec/The_Cooker.jpg",
                            ReleaseDate = 1958,
                            Title = "The Cooker"
                        },
                        new
                        {
                            Id = 7,
                            Image = "https://upload.wikimedia.org/wikipedia/commons/a/ad/Somethin%E2%80%99_Else.jpg",
                            ReleaseDate = 1958,
                            Title = "Somethin' Else"
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.Comments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Jazzima1.Models.InstrumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InstrumentType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Horn"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Piano"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Bass"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Drums"
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.Musician", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Instrument")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InstrumentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentTypeId");

                    b.ToTable("Musician");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Herbie Hancock"
                        },
                        new
                        {
                            Id = 2,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Freddie Hubbard"
                        },
                        new
                        {
                            Id = 3,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "George Coleman"
                        },
                        new
                        {
                            Id = 4,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Ron Carter"
                        },
                        new
                        {
                            Id = 5,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Tony Williams"
                        },
                        new
                        {
                            Id = 6,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Kenny Dorham"
                        },
                        new
                        {
                            Id = 7,
                            Instrument = "alto saxophone",
                            InstrumentTypeId = 1,
                            Name = "Eric Dolphy"
                        },
                        new
                        {
                            Id = 8,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Joe Henderson"
                        },
                        new
                        {
                            Id = 9,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Andrew Hill"
                        },
                        new
                        {
                            Id = 10,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Richard Davis"
                        },
                        new
                        {
                            Id = 11,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Wayne Shorter"
                        },
                        new
                        {
                            Id = 12,
                            Instrument = "alto saxophone",
                            InstrumentTypeId = 1,
                            Name = "James Spaulding"
                        },
                        new
                        {
                            Id = 13,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "McCoy Tyner"
                        },
                        new
                        {
                            Id = 14,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Horace Silver"
                        },
                        new
                        {
                            Id = 15,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "Hank Mobley"
                        },
                        new
                        {
                            Id = 16,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Doug Watkins"
                        },
                        new
                        {
                            Id = 17,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Art Blakey"
                        },
                        new
                        {
                            Id = 18,
                            Instrument = "drums",
                            InstrumentTypeId = 4,
                            Name = "Philly Joe Jones"
                        },
                        new
                        {
                            Id = 19,
                            Instrument = "bass",
                            InstrumentTypeId = 3,
                            Name = "Paul Chambers"
                        },
                        new
                        {
                            Id = 20,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Kenny Drew"
                        },
                        new
                        {
                            Id = 21,
                            Instrument = "trombone",
                            InstrumentTypeId = 1,
                            Name = "Curtis Fuller"
                        },
                        new
                        {
                            Id = 22,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Lee Morgan"
                        },
                        new
                        {
                            Id = 23,
                            Instrument = "tenor saxophone",
                            InstrumentTypeId = 1,
                            Name = "John Coltrane"
                        },
                        new
                        {
                            Id = 24,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Bobby Timmons"
                        },
                        new
                        {
                            Id = 25,
                            Instrument = "baritone saxophone",
                            InstrumentTypeId = 1,
                            Name = "Pepper Adams"
                        },
                        new
                        {
                            Id = 26,
                            Instrument = "alto saxophone",
                            InstrumentTypeId = 1,
                            Name = "Cannonball Adderley"
                        },
                        new
                        {
                            Id = 27,
                            Instrument = "trumpet",
                            InstrumentTypeId = 1,
                            Name = "Miles Davis"
                        },
                        new
                        {
                            Id = 28,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Hank Jones"
                        },
                        new
                        {
                            Id = 29,
                            Instrument = "piano",
                            InstrumentTypeId = 2,
                            Name = "Sam Jones"
                        },
                        new
                        {
                            Id = 30,
                            Instrument = "horns",
                            InstrumentTypeId = 1
                        },
                        new
                        {
                            Id = 31,
                            Instrument = "piano",
                            InstrumentTypeId = 2
                        },
                        new
                        {
                            Id = 32,
                            Instrument = "bass",
                            InstrumentTypeId = 3
                        },
                        new
                        {
                            Id = 33,
                            Instrument = "druma",
                            InstrumentTypeId = 4
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.MusicianAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("MusicianId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.HasIndex("MusicianId");

                    b.ToTable("MusicianAlbum");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            MusicianId = 1
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 1,
                            MusicianId = 2
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            MusicianId = 2
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 1,
                            MusicianId = 3
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 2,
                            MusicianId = 6
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 2,
                            MusicianId = 7
                        },
                        new
                        {
                            Id = 7,
                            AlbumId = 2,
                            MusicianId = 8
                        },
                        new
                        {
                            Id = 8,
                            AlbumId = 2,
                            MusicianId = 9
                        },
                        new
                        {
                            Id = 9,
                            AlbumId = 2,
                            MusicianId = 10
                        },
                        new
                        {
                            Id = 10,
                            AlbumId = 3,
                            MusicianId = 11
                        },
                        new
                        {
                            Id = 11,
                            AlbumId = 3,
                            MusicianId = 12
                        },
                        new
                        {
                            Id = 12,
                            AlbumId = 3,
                            MusicianId = 13
                        },
                        new
                        {
                            Id = 13,
                            AlbumId = 1,
                            MusicianId = 5
                        },
                        new
                        {
                            Id = 14,
                            AlbumId = 2,
                            MusicianId = 5
                        },
                        new
                        {
                            Id = 15,
                            AlbumId = 1,
                            MusicianId = 4
                        },
                        new
                        {
                            Id = 16,
                            AlbumId = 3,
                            MusicianId = 4
                        },
                        new
                        {
                            Id = 17,
                            AlbumId = 4,
                            MusicianId = 14
                        },
                        new
                        {
                            Id = 18,
                            AlbumId = 4,
                            MusicianId = 6
                        },
                        new
                        {
                            Id = 19,
                            AlbumId = 4,
                            MusicianId = 15
                        },
                        new
                        {
                            Id = 20,
                            AlbumId = 4,
                            MusicianId = 16
                        },
                        new
                        {
                            Id = 21,
                            AlbumId = 4,
                            MusicianId = 17
                        },
                        new
                        {
                            Id = 22,
                            AlbumId = 5,
                            MusicianId = 23
                        },
                        new
                        {
                            Id = 23,
                            AlbumId = 5,
                            MusicianId = 21
                        },
                        new
                        {
                            Id = 24,
                            AlbumId = 5,
                            MusicianId = 20
                        },
                        new
                        {
                            Id = 25,
                            AlbumId = 5,
                            MusicianId = 22
                        },
                        new
                        {
                            Id = 26,
                            AlbumId = 5,
                            MusicianId = 19
                        },
                        new
                        {
                            Id = 27,
                            AlbumId = 5,
                            MusicianId = 18
                        },
                        new
                        {
                            Id = 28,
                            AlbumId = 6,
                            MusicianId = 22
                        },
                        new
                        {
                            Id = 29,
                            AlbumId = 6,
                            MusicianId = 25
                        },
                        new
                        {
                            Id = 30,
                            AlbumId = 6,
                            MusicianId = 24
                        },
                        new
                        {
                            Id = 31,
                            AlbumId = 6,
                            MusicianId = 19
                        },
                        new
                        {
                            Id = 32,
                            AlbumId = 6,
                            MusicianId = 18
                        },
                        new
                        {
                            Id = 33,
                            AlbumId = 7,
                            MusicianId = 26
                        },
                        new
                        {
                            Id = 34,
                            AlbumId = 7,
                            MusicianId = 27
                        },
                        new
                        {
                            Id = 35,
                            AlbumId = 7,
                            MusicianId = 28
                        },
                        new
                        {
                            Id = 36,
                            AlbumId = 7,
                            MusicianId = 29
                        },
                        new
                        {
                            Id = 37,
                            AlbumId = 7,
                            MusicianId = 17
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.SavedAlbum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AlbumId");

                    b.ToTable("SavedAlbums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 1,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 2,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 3,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 4,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 5,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 6,
                            UserId = "00000000-ffff-ffff-ffff-ffffffffffff"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Jazzima1.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.HasData(
                        new
                        {
                            Id = "00000000-ffff-ffff-ffff-ffffffffffff",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ffb2fbc8-4f0c-4a80-a776-216586cb9b19",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEHD5Bj8EN/Iq903Ibg/BWjZI3amG/pU5xG1Gm1G2HboBD1fcJ98Ix1kz77FoLMYoxA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7f434309-a4d9-48e9-9ebb-8803db794577",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com",
                            FirstName = "admin",
                            LastName = "admin"
                        });
                });

            modelBuilder.Entity("Jazzima1.Models.Comments", b =>
                {
                    b.HasOne("Jazzima1.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jazzima1.Models.ApplicationUser", "ApplicationUser")
                        .WithMany()
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Jazzima1.Models.Musician", b =>
                {
                    b.HasOne("Jazzima1.Models.InstrumentType", "InstrumentType")
                        .WithMany()
                        .HasForeignKey("InstrumentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jazzima1.Models.MusicianAlbum", b =>
                {
                    b.HasOne("Jazzima1.Models.Album", "Album")
                        .WithMany("MusicianAlbums")
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Jazzima1.Models.Musician", "Musician")
                        .WithMany("MusicianAlbums")
                        .HasForeignKey("MusicianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Jazzima1.Models.SavedAlbum", b =>
                {
                    b.HasOne("Jazzima1.Models.Album", "Album")
                        .WithMany()
                        .HasForeignKey("AlbumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
